"""Generate deterministic program artifact + metadata (untrusted until reviewed/tested)."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from mainframe.promote.extract import extract_promotion
from mainframe.promote.types import PromotedProgram, TaskTrace

PROGRAM_TEMPLATE = '''\
# AUTO-GENERATED by mainframe.promote — UNTRUSTED until reviewed and tested.
# Not training data. Reuse of tested behavior only.
# source_trace: {trace_id}
# version: {version}
# trust: untrusted
# generality_claim: false

PROGRAM = {{
    "program_id": {program_id!r},
    "version": {version!r},
    "source_trace_id": {trace_id!r},
    "permissions": {permissions!r},
    "supported_conditions": {supported!r},
    "frozen_parameters": {frozen!r},
    "steps": {steps!r},
    "model_calls_avoided": {avoided!r},
    "rollback_path": {rollback!r},
}}

def describe() -> dict:
    return {{
        "program_id": PROGRAM["program_id"],
        "trust_required": "reviewed+tested",
        "generality_claim": False,
        "note": "One successful example is insufficient evidence of generality.",
    }}
'''


def promote_trace(
    trace: TaskTrace,
    *,
    out_dir: Path,
    program_id: str | None = None,
    previous: PromotedProgram | None = None,
) -> PromotedProgram:
    extracted = extract_promotion(trace)
    if not extracted.get("ok"):
        raise ValueError(extracted.get("error") or "extract_failed")

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    pid = program_id or f"promoted_{trace.source}_{trace.version}"
    version = "1" if previous is None else str(int(previous.version) + 1)
    rollback = None
    prev_ver = None
    if previous is not None:
        rollback = previous.program_path or previous.metadata_path
        prev_ver = previous.version

    prog = PromotedProgram(
        program_id=pid,
        version=version,
        trust="untrusted",
        source_trace_id=trace.trace_id,
        source=trace.source,
        permissions=extracted["permissions"],
        supported_conditions=extracted["supported_conditions"],
        steps=extracted["steps"],
        frozen_parameters=extracted["frozen_parameters"],
        model_calls_in_source=extracted["model_calls_in_source"],
        model_calls_in_program=extracted["model_calls_in_program"],
        model_calls_avoided=extracted["model_calls_avoided"],
        rollback_path=rollback,
        previous_version=prev_ver,
        generality_claim=False,
        review_notes=[
            "Generated program is untrusted until reviewed and tested against varied inputs and failure cases.",
            "Successful example is insufficient evidence of generality.",
            f"Removed steps: {json.dumps(extracted['removed_steps'])}",
        ],
    )

    meta_path = out_dir / f"{pid}_v{version}.meta.json"
    py_path = out_dir / f"{pid}_v{version}.py"
    py_path.write_text(
        PROGRAM_TEMPLATE.format(
            trace_id=trace.trace_id,
            version=version,
            program_id=pid,
            permissions=extracted["permissions"],
            supported=extracted["supported_conditions"],
            frozen=extracted["frozen_parameters"],
            steps=extracted["steps"],
            avoided=extracted["model_calls_avoided"],
            rollback=rollback,
        ),
        encoding="utf-8",
    )
    prog.program_path = str(py_path)
    prog.metadata_path = str(meta_path)
    meta_path.write_text(json.dumps(prog.to_dict(), indent=2) + "\n", encoding="utf-8")
    return prog


def load_program_meta(path: Path) -> PromotedProgram:
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    return PromotedProgram(**data)
