"""Build lightweight dependency + test map (no separate graph service)."""

from __future__ import annotations

import ast
import hashlib
import json
import re
from pathlib import Path
from typing import Any

from mainframe.codeintel.python_ast import _module_name, _walk_py, build_ast_index
from mainframe.codeintel.versions import content_version
from mainframe.depmap.uncertainty import uncertainty
from mainframe.inventory.ignore import should_skip_dir

BUILD_FILES = frozenset(
    {
        "pyproject.toml",
        "setup.py",
        "setup.cfg",
        "tox.ini",
        "pytest.ini",
        "Makefile",
        "package.json",
        "tsconfig.json",
        "Cargo.toml",
        "go.mod",
    }
)

DYNAMIC_CALL_NAMES = frozenset(
    {
        "__import__",
        "import_module",
        "getattr",
        "setattr",
        "hasattr",
        "globals",
        "locals",
        "eval",
        "exec",
    }
)

EXTERNAL_HINTS = re.compile(
    r"(?i)\b(requests\.(get|post|put|delete)|urllib\.request|httpx\.|aiohttp\.|"
    r"socket\.|ftp\.|smtp\.|boto3|s3\.|http://|https://)\b"
)

GENERATED_HINTS = re.compile(
    r"(?i)(autogenerated|generated by|do not edit|codegen|\.pb\.py$|_pb2\.py$|"
    r"\.g\.ts$|\.min\.js$)"
)


def _sha_files(root: Path, rels: list[str]) -> str:
    h = hashlib.sha256()
    for rel in sorted(set(rels)):
        p = root / rel
        h.update(rel.encode())
        try:
            h.update(p.read_bytes())
        except OSError:
            h.update(b"?")
    return h.hexdigest()


def _package_of(rel: str) -> str:
    parts = rel.replace("\\", "/").split("/")
    if len(parts) >= 2:
        return parts[0]
    return "."


def _is_test_path(rel: str) -> bool:
    name = Path(rel).name
    lower = rel.replace("\\", "/").lower()
    return (
        name.startswith("test_")
        or name.endswith("_test.py")
        or "/tests/" in f"/{lower}/"
        or name.startswith("test")
        and name.endswith(".py")
    )


def detect_dynamic_and_reflection(tree: ast.AST, rel: str) -> list[dict[str, Any]]:
    found: list[dict[str, Any]] = []

    class V(ast.NodeVisitor):
        def visit_Call(self, node: ast.Call) -> None:
            name = None
            if isinstance(node.func, ast.Name):
                name = node.func.id
            elif isinstance(node.func, ast.Attribute):
                name = node.func.attr
            if name in DYNAMIC_CALL_NAMES:
                # Static string arg → still note but may be resolvable later
                static = None
                if node.args and isinstance(node.args[0], ast.Constant) and isinstance(
                    node.args[0].value, str
                ):
                    static = node.args[0].value
                kind = "dynamic_import" if name in {"__import__", "import_module"} else "reflection"
                found.append(
                    uncertainty(
                        kind,  # type: ignore[arg-type]
                        path=rel,
                        detail=f"{name}() at line {node.lineno}"
                        + (f" static={static!r}" if static else " (non-static target)"),
                        widens_plan=static is None,
                    )
                )
            self.generic_visit(node)

        def visit_Attribute(self, node: ast.Attribute) -> None:
            # obj.__dict__ / __getattribute__ style reflection hints
            if node.attr in {"__dict__", "__getattribute__", "__getattr__", "__class__"}:
                found.append(
                    uncertainty(
                        "reflection",
                        path=rel,
                        detail=f"attribute {node.attr} line {getattr(node, 'lineno', 0)}",
                    )
                )
            self.generic_visit(node)

    V().visit(tree)
    return found


def build_map(
    root: Path,
    *,
    observed_runs: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """
    Construct dependency/test map from imports, packages, build files, observed runs.

    Edges are observed facts only; uncertainty entries flag incomplete knowledge.
    """
    root = root.resolve()
    idx = build_ast_index(root)

    modules: dict[str, dict[str, Any]] = {}
    edges: list[dict[str, Any]] = []  # importer -> importee (static)
    uncertainties: list[dict[str, Any]] = []
    tests: dict[str, dict[str, Any]] = {}
    packages: dict[str, list[str]] = {}
    build_files: list[str] = []
    file_hashes: dict[str, str] = {}

    # Build / config files
    for dirpath, dirnames, filenames in __import__("os").walk(root, followlinks=False):
        dirnames[:] = [d for d in dirnames if not should_skip_dir(d)]
        base = Path(dirpath)
        for name in filenames:
            full = base / name
            try:
                rel = full.relative_to(root).as_posix()
            except ValueError:
                continue
            if name in BUILD_FILES or rel.startswith(".github/workflows/"):
                build_files.append(rel)
                ver = content_version(full)
                if ver.get("sha256"):
                    file_hashes[rel] = ver["sha256"]

    for rel, lines in idx.files.items():
        ver = idx.versions.get(rel) or {}
        if ver.get("sha256"):
            file_hashes[rel] = ver["sha256"]
        mod = _module_name(root, rel)
        pkg = _package_of(rel)
        packages.setdefault(pkg, []).append(rel)
        text = "\n".join(lines)
        modules[rel] = {
            "module": mod,
            "package": pkg,
            "is_test": _is_test_path(rel),
            "sha256": ver.get("sha256"),
        }
        if _is_test_path(rel):
            tests[rel] = {
                "module": mod,
                "package": pkg,
                "imports": [],
                "verify_command": f'python -m pytest "{rel}" -q',
            }

        # Static imports → edges
        for im in idx.imports.get(rel, []):
            target_mod = im.get("module") or ""
            if im["kind"] == "from" and im.get("name") and im.get("name") != "*":
                # from pkg.x import y — dependency on pkg.x (and possibly pkg.x.y module)
                target_mod = im.get("module") or ""
            if not target_mod:
                continue
            # Resolve to local file if possible
            target_rel = _resolve_local_module(root, target_mod, idx.files.keys())
            edge = {
                "from": rel,
                "to_module": target_mod,
                "to_path": target_rel,
                "kind": "static_import",
                "lineno": im.get("lineno"),
                "observed": True,
            }
            edges.append(edge)
            if rel in tests:
                tests[rel]["imports"].append(target_mod)

        # Dynamic / reflection
        try:
            tree = ast.parse(text, filename=rel)
            uncertainties.extend(detect_dynamic_and_reflection(tree, rel))
        except SyntaxError:
            uncertainties.append(
                uncertainty(
                    "map_incomplete",
                    path=rel,
                    detail="syntax_error_while_parsing",
                )
            )

        if GENERATED_HINTS.search(text) or GENERATED_HINTS.search(rel):
            uncertainties.append(
                uncertainty(
                    "generated_code",
                    path=rel,
                    detail="Generated-code marker or path heuristic",
                )
            )
        if EXTERNAL_HINTS.search(text):
            uncertainties.append(
                uncertainty(
                    "external_service",
                    path=rel,
                    detail="External HTTP/network/service API usage observed in source",
                )
            )

    # Observed test runs enrich map (do not invent coverage)
    observed_runs = observed_runs or []
    for run in observed_runs:
        tpath = (run.get("test_path") or "").replace("\\", "/")
        if tpath and tpath in tests:
            tests[tpath]["observed_runs"] = tests[tpath].get("observed_runs", []) + [run]
            for touched in run.get("touched_modules") or []:
                # Record observed runtime dependency edge
                edges.append(
                    {
                        "from": tpath,
                        "to_module": touched,
                        "to_path": _resolve_local_module(root, touched, idx.files.keys()),
                        "kind": "observed_test_run",
                        "observed": True,
                    }
                )

    # Mark unresolved dynamic imports explicitly
    for u in uncertainties:
        if u["kind"] == "dynamic_import" and not u.get("resolved"):
            edges.append(
                {
                    "from": u.get("path"),
                    "to_module": None,
                    "to_path": None,
                    "kind": "dynamic_import_unresolved",
                    "observed": False,
                    "uncertainty": u,
                }
            )

    config_hash = _sha_files(root, build_files)
    content_hash = hashlib.sha256(
        "".join(f"{k}:{v}" for k, v in sorted(file_hashes.items())).encode()
    ).hexdigest()

    incomplete = any(u.get("widens_plan") for u in uncertainties) or any(
        e.get("kind") == "dynamic_import_unresolved" for e in edges
    )

    return {
        "ok": True,
        "root": str(root),
        "modules": modules,
        "packages": {k: sorted(v) for k, v in packages.items()},
        "edges": edges,
        "tests": tests,
        "build_files": sorted(build_files),
        "uncertainties": uncertainties,
        "incomplete": incomplete,
        "absence_not_proven": True,
        "cache_key": {
            "config_hash": config_hash,
            "content_hash": content_hash,
            "file_count": len(file_hashes),
        },
        "file_hashes": file_hashes,
        "graph_service_used": False,
        "model_service_used": False,
    }


def _resolve_local_module(root: Path, module: str, known_rels) -> str | None:
    """Map dotted module to a relative path inside root if present."""
    mod = module.replace("\\", "/").replace("/", ".")
    candidates = [
        mod.replace(".", "/") + ".py",
        mod.replace(".", "/") + "/__init__.py",
    ]
    known = set(known_rels)
    for c in candidates:
        if c in known:
            return c
    # Suffix match (e.g. import util when packages/alpha/util.py)
    suffix = mod.split(".")[-1] + ".py"
    hits = [r for r in known if r.endswith("/" + suffix) or r == suffix]
    if len(hits) == 1:
        return hits[0]
    return None
